[project]
name = "trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "ccxt>=4.5.4",
    "loguru>=0.7.3",
    "numpy>=2.3.3",
    "polars>=1.33.1",
    "python-dotenv>=1.1.1",
]
